apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c5n8ggd3t-python
  janus-idp.io/tekton: c5n8ggd3t-python
  backstage.io/kubernetes-id: c5n8ggd3t-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c5n8ggd3t-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
