apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: c5n8ggd3t-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c5n8ggd3t-python 
  name: c5n8ggd3t-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: c5n8ggd3t-python 
